Make cart subtotal data type from `integer` to `float`
vtex-apps/order-quote pull request #26
Opened 2020-12-21 09:56 UTC by Jayendra88

#### What does this PR do?
When we create a quote with large number of items which has subtotal greater than max value of `Int 32` will return an error response to the user. 
Since graphql schema allows `Float` value for cart `total`, I think we should allow `subtotal` also be `Float`.

#### How to test it? 
you can test this functionality in this [workspace](https://clouda--ecowaterb2b.myvtex.com/orderquote)

2020-12-21 09:57 UTC, Jayendra88 commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2020-12-21 09:57 UTC, Jayendra88 commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2020-12-21 15:24 UTC, wender requested changes
It would be good to update the Schema version too otherwise it will not update to other customers

2020-12-22 03:58 UTC, Jayendra88 commented
Done

2020-12-22 04:01 UTC, Jayendra88 commented
> It would be good to update the Schema version too otherwise it will not update to other customers

Done

2021-01-12 14:29 UTC, wender requested changes

2021-01-12 14:29 UTC, wender commented on CHANGELOG.md
> +## [1.2.4] - 2021-01-12
Remove the version, CI will do it automatically if it's under [Unreleased]

2021-01-12 14:29 UTC, wender commented on manifest.json
> +  "version": "1.2.4",
Keep the same version as the original, CI will update the version automatically

2021-01-12 16:42 UTC, Jayendra88 commented on CHANGELOG.md
> +## [1.2.4] - 2021-01-12
fixed

2021-01-12 16:42 UTC, Jayendra88 commented on manifest.json
> +  "version": "1.2.4",
fixed

2021-01-12 17:18 UTC, wender approved these changes

2021-01-12 17:19 UTC, merged