Add order quote link to My account menu
vtex-apps/order-quote pull request #48
Opened 2021-12-03 08:22 UTC by adiopris

#### What does this PR do? \*

      Add order quote link to My account menu
#### How to test it? \*

##### 1. Add on manifest.json -> peerDependencies

      "vtex.orderquote": "1.x"

##### 2. Add these blocks on blocks.jsonc

    "oq-link": {}, 

    "my-account-page.order-quote-page": {} 
#### Describe alternatives you've considered, if any. \*

#### Related to / Depends on \*

2021-12-03 08:47 UTC, adiopris commented
Is required a simple patch release. 
Thank you!

2021-12-07 12:58 UTC, adiopris commented
@wender

2021-12-14 16:33 UTC, polishq requested changes
A few changes, please:

- Do not make any modifications to PULL_REQUEST_TEMPLATE.md
- Rather than instructing users to modify their store-theme, I propose that this app should automatically insert the Order Quote link into the My Account sidebar
- The Order Quote link text should be internationalized, for an example see here: https://github.com/vtex-apps/b2b-organizations/blob/master/react/MyOrganizationLink.tsx#L15

2021-12-15 15:06 UTC, adiopris commented
Hi @polishq,

I made the requested changes.
Unfortunately that blocks are required to be added in store-theme blocks.json file, in order to display an 'Order quote' entry on My Account menu.

Thank you!

2021-12-15 15:26 UTC, polishq commented
> Hi @polishq,
> 
> I made the requested changes. Unfortunately that blocks are required to be added in store-theme blocks.json file, in order to display an 'Order quote' entry on My Account menu.
> 
> Thank you!

Actually, it is possible for the app to do this automatically with a plugins.json file. See here for example: https://github.com/vtex-apps/b2b-organizations/blob/master/store/plugins.json

2021-12-15 22:23 UTC, polishq commented
> I linked up the app and in store-theme I have error of missing block order-quote.

This part sounds strange to me, please try removing any reference to `order-quote` from the store-theme JSON. Additionally, try removing `store/pages.json` from the order-quote app.

You should just need:
- two interfaces like this: https://github.com/vtex-apps/b2b-organizations/blob/master/store/interfaces.json#L1-L7
- two plugins like this: https://github.com/vtex-apps/b2b-organizations/blob/master/store/plugins.json
- a link component like this: https://github.com/vtex-apps/b2b-organizations/blob/master/react/MyOrganizationLink.tsx
- and a router component like this: https://github.com/vtex-apps/b2b-organizations/blob/master/react/MyOrganizationPage.tsx (with just one <Route> in your case)

2021-12-16 08:58 UTC, adiopris commented
Hi Arthur,
Parhaps existence of 'store/pages.json' file, were the main issue here. 
After I deleted it, everything has reverted to normal.

Thank you for your support!

2021-12-21 14:53 UTC, polishq requested changes
In addition to the above comment, please make sure you have Prettier and ESLint enabled in your code editor. I'm seeing various lint errors when viewing your code:
<img width="732" alt="quote-lint" src="https://user-images.githubusercontent.com/6306265/146950011-b2d327bf-fbac-4608-9356-72b5a1498f67.png">

2021-12-21 14:53 UTC, polishq commented on react/OrderQuoteListAccount.tsx
> +  window.location.href ='/orderquote'
This results in the user being redirected outside of the My Account interface, is that intended? It seems like strange behavior.

2022-01-04 15:26 UTC, adiopris commented on react/OrderQuoteListAccount.tsx
> +  window.location.href ='/orderquote'
I fixed the lint errors. 
Regarding '/orderquote' redirect, I choosed this behavior, because I cannot alter another app links likes 'View details' or 'New'. So I prefer to use My Account menu item as a shortcut to the app and to keep all app links in the same format.

If I set the redirect to remain in My account (displaying My Account menu), the order quote listing will remain here but not the 'New' or 'View' pages where the app will be loaded outside of My Account.

2022-01-12 07:55 UTC, adiopris commented
Hi @polishq,
I made ESLint and Prettier changes. I use PHPStorm and with my configuration it looks good.
If issues persist on your side, please send me your tsconfig and eslint configuration.

2022-01-13 14:16 UTC, polishq commented on react/OrderQuoteListAccount.tsx
> +  window.location.href ='/orderquote'
I'd like to avoid the "flicker" if possible. The app appears to load inside the My Account interface and then the user gets redirected, which looks odd. Can you see if it's possible for the My Account link to point directly to `/orderquote`, rather than relying on `window.location.href` ? 

If that's not possible, then I would recommend removing the `QuoteList` component from this file. Perhaps just render a Spinner until the redirect completes.

2022-01-13 14:17 UTC, polishq commented
> Hi @polishq, I made ESLint and Prettier changes. I use PHPStorm and with my configuration it looks good. If issues persist on your side, please send me your tsconfig and eslint configuration.

@adiopris See comment added above

2022-01-14 13:17 UTC, adiopris commented on react/OrderQuoteListAccount.tsx
> +  window.location.href ='/orderquote'
I removed window.location.href.

2022-01-17 17:18 UTC, adiopris commented
@polishq I removed the window.location.href. Can you confirm please that everything is good?!

2022-01-20 21:56 UTC, polishq approved these changes

2022-01-20 21:58 UTC, merged

2022-01-20 21:59 UTC, polishq commented
Thanks for your patience @adiopris , the new version has been published!